development: &development
  host: 'http://local.host:8080'
  namespace: '/nodevent'

test: &test
  host: 'http://localhost:8080'
  namespace: '/nodevent'

cucumber:
  <<: *test

staging:
  host: 'http://alpha.positivebid.com:8080'
  namespace: '/positive'

production:
  host: 'http://www.positivebid.com:8080'
  namespace: '/positive'
  

